version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
  
  server:
    build:
      context: ./TechKart-Server
      dockerfile: Dockerfile.dev
    container_name: techkart-server
    ports:
      - "4000:4000"
    env_file:
      - ./TechKart-Server/.env
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:password@mongodb:27017/techkart?authSource=admin
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    develop:
      watch:
        - path: ./TechKart-Server/package*.json
          action: rebuild
        - path: ./TechKart-Server/src
          target: /app/src
          action: sync
 
  client:
    build:
      context: ./TechKart-Frontend
      dockerfile: Dockerfile.dev
    container_name: techkart-client
    ports:
      - "5173:5173"
    env_file:
      - ./TechKart-Frontend/.env
    depends_on:
      - server
    develop:
      watch:
        - path: ./TechKart-Frontend/package*.json
          action: rebuild
        - path: ./TechKart-Frontend/src
          target: /app/src
          action: sync
  
volumes:
  mongodb_data:
     driver: local